---
- include_tasks: "download_{{ ansible_facts.pkg_mgr }}.yml"
- include_tasks: "install_{{ ansible_facts.pkg_mgr }}.yml"
- import_tasks: configure.yml
- import_tasks: set.yml
- import_tasks: load.yml

# tasks file for filebeat-role
